CREATE TABLE `erp_data_import_batches` (`id` text PRIMARY KEY NOT NULL,`source_id` text NOT NULL,`status` text DEFAULT 'UPLOADED' NOT NULL,`file_name` text NOT NULL,`content_type` text NOT NULL,`storage_key` text NOT NULL,`file_sha256` text NOT NULL,`byte_size` integer DEFAULT 0 NOT NULL,`parser_type` text NOT NULL,`header_json` text DEFAULT '[]' NOT NULL,`mapping_json` text DEFAULT '{}' NOT NULL,`total_rows` integer DEFAULT 0 NOT NULL,`valid_rows` integer DEFAULT 0 NOT NULL,`invalid_rows` integer DEFAULT 0 NOT NULL,`duplicate_rows` integer DEFAULT 0 NOT NULL,`create_rows` integer DEFAULT 0 NOT NULL,`update_rows` integer DEFAULT 0 NOT NULL,`skip_rows` integer DEFAULT 0 NOT NULL,`approval_request_id` text DEFAULT '' NOT NULL,`requested_by` text NOT NULL,`submitted_at` integer,`approved_at` integer,`applied_at` integer,`applied_by` text DEFAULT '' NOT NULL,`failure_message` text DEFAULT '' NOT NULL,`version` integer DEFAULT 1 NOT NULL,`created_at` integer NOT NULL,`updated_at` integer NOT NULL);--> statement-breakpoint
CREATE UNIQUE INDEX `idx_erp_data_import_source_hash` ON `erp_data_import_batches` (`source_id`,`file_sha256`);--> statement-breakpoint
CREATE INDEX `idx_erp_data_import_status_created` ON `erp_data_import_batches` (`status`,`created_at`);--> statement-breakpoint
CREATE TABLE `erp_data_import_rows` (`id` text PRIMARY KEY NOT NULL,`batch_id` text NOT NULL,`row_number` integer NOT NULL,`raw_json` text NOT NULL,`normalized_json` text DEFAULT '{}' NOT NULL,`identity_key` text DEFAULT '' NOT NULL,`row_checksum` text NOT NULL,`validation_status` text DEFAULT 'VALID' NOT NULL,`issues_json` text DEFAULT '[]' NOT NULL,`proposed_action` text DEFAULT 'SKIP' NOT NULL,`target_entity_type` text DEFAULT '' NOT NULL,`target_entity_id` text DEFAULT '' NOT NULL,`applied_at` integer,`created_at` integer NOT NULL);--> statement-breakpoint
CREATE UNIQUE INDEX `idx_erp_data_import_row_number` ON `erp_data_import_rows` (`batch_id`,`row_number`);--> statement-breakpoint
CREATE INDEX `idx_erp_data_import_row_validation` ON `erp_data_import_rows` (`batch_id`,`validation_status`,`proposed_action`);--> statement-breakpoint
CREATE INDEX `idx_erp_data_import_row_identity` ON `erp_data_import_rows` (`batch_id`,`identity_key`);--> statement-breakpoint
CREATE TABLE `erp_data_import_events` (`id` text PRIMARY KEY NOT NULL,`batch_id` text NOT NULL,`action` text NOT NULL,`from_status` text DEFAULT '' NOT NULL,`to_status` text DEFAULT '' NOT NULL,`actor_employee_id` text NOT NULL,`note` text DEFAULT '' NOT NULL,`snapshot_json` text DEFAULT '{}' NOT NULL,`created_at` integer NOT NULL);--> statement-breakpoint
CREATE INDEX `idx_erp_data_import_event_batch_created` ON `erp_data_import_events` (`batch_id`,`created_at`);--> statement-breakpoint
PRAGMA optimize;
