CREATE TABLE `finance_import_mapping_sets` (`id` text PRIMARY KEY NOT NULL,`source_id` text NOT NULL,`name` text NOT NULL,`data_type` text NOT NULL,`version` integer DEFAULT 1 NOT NULL,`status` text DEFAULT 'DRAFT' NOT NULL,`field_mapping_json` text DEFAULT '{}' NOT NULL,`approval_request_id` text DEFAULT '' NOT NULL,`created_by` text NOT NULL,`approved_by` text DEFAULT '' NOT NULL,`submitted_at` integer,`approved_at` integer,`created_at` integer NOT NULL,`updated_at` integer NOT NULL);--> statement-breakpoint
CREATE UNIQUE INDEX `idx_finance_import_mapping_version` ON `finance_import_mapping_sets` (`source_id`,`data_type`,`version`);--> statement-breakpoint
CREATE UNIQUE INDEX `idx_finance_import_mapping_active` ON `finance_import_mapping_sets` (`source_id`,`data_type`) WHERE `status` = 'ACTIVE';--> statement-breakpoint
CREATE INDEX `idx_finance_import_mapping_status` ON `finance_import_mapping_sets` (`status`,`updated_at`);--> statement-breakpoint
CREATE TABLE `finance_import_mapping_rules` (`id` text PRIMARY KEY NOT NULL,`mapping_set_id` text NOT NULL,`dimension_type` text NOT NULL,`source_key` text NOT NULL,`source_label` text DEFAULT '' NOT NULL,`target_id` text DEFAULT '' NOT NULL,`target_code` text DEFAULT '' NOT NULL,`target_label` text DEFAULT '' NOT NULL,`mapping_method` text DEFAULT 'MANUAL' NOT NULL,`created_by` text NOT NULL,`created_at` integer NOT NULL,`updated_at` integer NOT NULL);--> statement-breakpoint
CREATE UNIQUE INDEX `idx_finance_import_rule_key` ON `finance_import_mapping_rules` (`mapping_set_id`,`dimension_type`,`source_key`);--> statement-breakpoint
CREATE INDEX `idx_finance_import_rule_target` ON `finance_import_mapping_rules` (`dimension_type`,`target_id`);--> statement-breakpoint
CREATE TABLE `finance_import_validations` (`id` text PRIMARY KEY NOT NULL,`batch_id` text NOT NULL,`mapping_set_id` text NOT NULL,`data_type` text NOT NULL,`status` text NOT NULL,`row_count` integer DEFAULT 0 NOT NULL,`valid_count` integer DEFAULT 0 NOT NULL,`invalid_count` integer DEFAULT 0 NOT NULL,`account_mapped_count` integer DEFAULT 0 NOT NULL,`partner_mapped_count` integer DEFAULT 0 NOT NULL,`department_mapped_count` integer DEFAULT 0 NOT NULL,`total_debit` integer DEFAULT 0 NOT NULL,`total_credit` integer DEFAULT 0 NOT NULL,`difference_amount` integer DEFAULT 0 NOT NULL,`result_json` text DEFAULT '{}' NOT NULL,`created_by` text NOT NULL,`created_at` integer NOT NULL);--> statement-breakpoint
CREATE INDEX `idx_finance_import_validation_batch_created` ON `finance_import_validations` (`batch_id`,`created_at`);--> statement-breakpoint
CREATE TABLE `finance_import_canonical_rows` (`id` text PRIMARY KEY NOT NULL,`validation_id` text NOT NULL,`batch_id` text NOT NULL,`row_number` integer NOT NULL,`record_type` text NOT NULL,`record_key` text DEFAULT '' NOT NULL,`canonical_json` text DEFAULT '{}' NOT NULL,`validation_status` text NOT NULL,`issues_json` text DEFAULT '[]' NOT NULL,`source_checksum` text NOT NULL,`created_at` integer NOT NULL);--> statement-breakpoint
CREATE UNIQUE INDEX `idx_finance_import_canonical_row` ON `finance_import_canonical_rows` (`validation_id`,`row_number`);--> statement-breakpoint
CREATE INDEX `idx_finance_import_canonical_batch_status` ON `finance_import_canonical_rows` (`batch_id`,`validation_status`);--> statement-breakpoint
CREATE TABLE `finance_import_mapping_events` (`id` text PRIMARY KEY NOT NULL,`mapping_set_id` text NOT NULL,`action` text NOT NULL,`from_status` text DEFAULT '' NOT NULL,`to_status` text DEFAULT '' NOT NULL,`actor_employee_id` text NOT NULL,`note` text DEFAULT '' NOT NULL,`snapshot_json` text DEFAULT '{}' NOT NULL,`created_at` integer NOT NULL);--> statement-breakpoint
CREATE INDEX `idx_finance_import_mapping_event_created` ON `finance_import_mapping_events` (`mapping_set_id`,`created_at`);--> statement-breakpoint
PRAGMA optimize;
