CREATE TABLE `finance_posting_batches` (`id` text PRIMARY KEY NOT NULL,`validation_id` text DEFAULT '' NOT NULL,`source_batch_id` text DEFAULT '' NOT NULL,`batch_number` text NOT NULL,`source_type` text DEFAULT 'IMPORT' NOT NULL,`reversal_of_batch_id` text DEFAULT '' NOT NULL,`status` text DEFAULT 'DRAFT' NOT NULL,`period_from` text NOT NULL,`period_to` text NOT NULL,`voucher_count` integer DEFAULT 0 NOT NULL,`line_count` integer DEFAULT 0 NOT NULL,`total_debit` integer DEFAULT 0 NOT NULL,`total_credit` integer DEFAULT 0 NOT NULL,`difference_amount` integer DEFAULT 0 NOT NULL,`approval_request_id` text DEFAULT '' NOT NULL,`reason` text DEFAULT '' NOT NULL,`prepared_by` text NOT NULL,`approved_by` text DEFAULT '' NOT NULL,`posted_by` text DEFAULT '' NOT NULL,`submitted_at` integer,`approved_at` integer,`posted_at` integer,`version` integer DEFAULT 1 NOT NULL,`created_at` integer NOT NULL,`updated_at` integer NOT NULL);--> statement-breakpoint
CREATE UNIQUE INDEX `idx_finance_posting_validation` ON `finance_posting_batches` (`validation_id`) WHERE `validation_id` <> '';--> statement-breakpoint
CREATE UNIQUE INDEX `idx_finance_posting_reversal` ON `finance_posting_batches` (`reversal_of_batch_id`) WHERE `reversal_of_batch_id` <> '';--> statement-breakpoint
CREATE UNIQUE INDEX `idx_finance_posting_batch_number` ON `finance_posting_batches` (`batch_number`);--> statement-breakpoint
CREATE INDEX `idx_finance_posting_status_period` ON `finance_posting_batches` (`status`,`period_from`,`period_to`);--> statement-breakpoint
CREATE TABLE `finance_posting_vouchers` (`id` text PRIMARY KEY NOT NULL,`batch_id` text NOT NULL,`source_voucher_key` text NOT NULL,`voucher_date` text NOT NULL,`period` text NOT NULL,`voucher_number` text DEFAULT '' NOT NULL,`description` text DEFAULT '' NOT NULL,`source_reference` text DEFAULT '' NOT NULL,`status` text DEFAULT 'DRAFT' NOT NULL,`line_count` integer DEFAULT 0 NOT NULL,`total_debit` integer DEFAULT 0 NOT NULL,`total_credit` integer DEFAULT 0 NOT NULL,`created_at` integer NOT NULL,`updated_at` integer NOT NULL);--> statement-breakpoint
CREATE UNIQUE INDEX `idx_finance_posting_source_voucher` ON `finance_posting_vouchers` (`batch_id`,`source_voucher_key`);--> statement-breakpoint
CREATE UNIQUE INDEX `idx_finance_posting_voucher_number` ON `finance_posting_vouchers` (`voucher_number`) WHERE `voucher_number` <> '';--> statement-breakpoint
CREATE INDEX `idx_finance_posting_voucher_period` ON `finance_posting_vouchers` (`period`,`status`);--> statement-breakpoint
CREATE TABLE `finance_posting_lines` (`id` text PRIMARY KEY NOT NULL,`voucher_id` text NOT NULL,`line_number` integer NOT NULL,`account_id` text NOT NULL,`account_code` text NOT NULL,`account_name` text NOT NULL,`partner_id` text DEFAULT '' NOT NULL,`partner_name` text DEFAULT '' NOT NULL,`department_id` text DEFAULT '' NOT NULL,`department_name` text DEFAULT '' NOT NULL,`tax_code_id` text DEFAULT '' NOT NULL,`tax_code` text DEFAULT '' NOT NULL,`tax_code_name` text DEFAULT '' NOT NULL,`tax_review_status` text DEFAULT 'PENDING' NOT NULL,`tax_review_note` text DEFAULT '' NOT NULL,`tax_reviewed_by` text DEFAULT '' NOT NULL,`tax_reviewed_at` integer,`description` text DEFAULT '' NOT NULL,`debit_amount` integer DEFAULT 0 NOT NULL,`credit_amount` integer DEFAULT 0 NOT NULL,`source_canonical_row_id` text DEFAULT '' NOT NULL,`source_checksum` text DEFAULT '' NOT NULL,`reversal_of_line_id` text DEFAULT '' NOT NULL,`created_at` integer NOT NULL,`updated_at` integer NOT NULL);--> statement-breakpoint
CREATE UNIQUE INDEX `idx_finance_posting_line_number` ON `finance_posting_lines` (`voucher_id`,`line_number`);--> statement-breakpoint
CREATE UNIQUE INDEX `idx_finance_posting_source_row` ON `finance_posting_lines` (`source_canonical_row_id`) WHERE `source_canonical_row_id` <> '';--> statement-breakpoint
CREATE UNIQUE INDEX `idx_finance_posting_reversal_line` ON `finance_posting_lines` (`reversal_of_line_id`) WHERE `reversal_of_line_id` <> '';--> statement-breakpoint
CREATE INDEX `idx_finance_posting_tax_review` ON `finance_posting_lines` (`tax_review_status`,`tax_code_id`);--> statement-breakpoint
CREATE TABLE `finance_posting_events` (`id` text PRIMARY KEY NOT NULL,`batch_id` text NOT NULL,`action` text NOT NULL,`from_status` text DEFAULT '' NOT NULL,`to_status` text DEFAULT '' NOT NULL,`actor_employee_id` text NOT NULL,`note` text DEFAULT '' NOT NULL,`snapshot_json` text DEFAULT '{}' NOT NULL,`created_at` integer NOT NULL);--> statement-breakpoint
CREATE INDEX `idx_finance_posting_event_created` ON `finance_posting_events` (`batch_id`,`created_at`);--> statement-breakpoint
PRAGMA optimize;
