CREATE TABLE `finance_opening_balance_sets` (`id` text PRIMARY KEY NOT NULL,`fiscal_year` integer NOT NULL,`version` integer DEFAULT 1 NOT NULL,`status` text DEFAULT 'DRAFT' NOT NULL,`source_label` text NOT NULL,`source_as_of` text NOT NULL,`source_checksum` text NOT NULL,`line_count` integer DEFAULT 0 NOT NULL,`total_debit` integer DEFAULT 0 NOT NULL,`total_credit` integer DEFAULT 0 NOT NULL,`difference_amount` integer DEFAULT 0 NOT NULL,`approval_request_id` text DEFAULT '' NOT NULL,`reason` text DEFAULT '' NOT NULL,`prepared_by` text NOT NULL,`approved_by` text DEFAULT '' NOT NULL,`submitted_at` integer,`approved_at` integer,`created_at` integer NOT NULL,`updated_at` integer NOT NULL);--> statement-breakpoint
CREATE UNIQUE INDEX `idx_finance_opening_year_version` ON `finance_opening_balance_sets` (`fiscal_year`,`version`);--> statement-breakpoint
CREATE UNIQUE INDEX `idx_finance_opening_approved_year` ON `finance_opening_balance_sets` (`fiscal_year`) WHERE `status`='APPROVED';--> statement-breakpoint
CREATE TABLE `finance_opening_balance_lines` (`id` text PRIMARY KEY NOT NULL,`set_id` text NOT NULL,`line_number` integer NOT NULL,`account_id` text DEFAULT '' NOT NULL,`account_code` text NOT NULL,`account_name` text NOT NULL,`account_category` text NOT NULL,`normal_balance` text NOT NULL,`debit_amount` integer DEFAULT 0 NOT NULL,`credit_amount` integer DEFAULT 0 NOT NULL,`source_reference` text DEFAULT '' NOT NULL,`created_at` integer NOT NULL);--> statement-breakpoint
CREATE UNIQUE INDEX `idx_finance_opening_line_number` ON `finance_opening_balance_lines` (`set_id`,`line_number`);--> statement-breakpoint
CREATE UNIQUE INDEX `idx_finance_opening_line_account` ON `finance_opening_balance_lines` (`set_id`,`account_code`,`account_name`);--> statement-breakpoint
CREATE TABLE `finance_opening_balance_events` (`id` text PRIMARY KEY NOT NULL,`set_id` text NOT NULL,`action` text NOT NULL,`from_status` text DEFAULT '' NOT NULL,`to_status` text DEFAULT '' NOT NULL,`actor_employee_id` text NOT NULL,`note` text DEFAULT '' NOT NULL,`snapshot_json` text DEFAULT '{}' NOT NULL,`created_at` integer NOT NULL);--> statement-breakpoint
CREATE INDEX `idx_finance_opening_event_created` ON `finance_opening_balance_events` (`set_id`,`created_at`);--> statement-breakpoint
PRAGMA optimize;
