"use client";

import { useEffect, useMemo, useState } from "react";
import OpeningBalanceControl from "./opening-balance-control";

type Row = Record<string, string | number | boolean | null>;
type LedgerData = { asOf:string; from:string; to:string; accounts:Row[]; rows:Row[];
  pagination:{returned:number;total:number;limit:number}; totals:Record<string,number>;
  sources:{opening:{label:string;asOf:string;immutableReference:boolean};controlledPostingLines:number;paymentJournalLines:number;postedOnly:boolean;stagedOrClobeRowsIncluded:boolean};
  controls:{balanced:boolean;openingApprovedReference:boolean;sourceMutation:boolean;directClobePosting:boolean} };
const won=(value:unknown)=>`${Number(value??0).toLocaleString("ko-KR")}원`;
const dateTime=(value:unknown)=>value?new Date(Number(value)).toLocaleString("ko-KR",{dateStyle:"short",timeStyle:"short"}):"—";

export default function GeneralLedgerWorkspace(){
  const [data,setData]=useState<LedgerData|null>(null);const [from,setFrom]=useState("2026-01-01");const [to,setTo]=useState("");
  const [account,setAccount]=useState("");const [query,setQuery]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  async function load(nextFrom=from,nextTo=to,nextAccount=account,nextQuery=query){setBusy(true);setError("");try{const params=new URLSearchParams({from:nextFrom});if(nextTo)params.set("to",nextTo);if(nextAccount)params.set("account",nextAccount);if(nextQuery.trim())params.set("q",nextQuery.trim());const response=await fetch(`/api/finance/general-ledger?${params}`,{cache:"no-store"});const payload=await response.json() as LedgerData&{error?:string};if(!response.ok)throw new Error(payload.error||"총계정원장을 불러오지 못했습니다.");setData(payload);setTo(payload.to);}catch(caught){setError(caught instanceof Error?caught.message:"총계정원장을 불러오지 못했습니다.");}finally{setBusy(false);}}
  useEffect(()=>{let cancelled=false;fetch("/api/finance/general-ledger",{cache:"no-store"}).then(async(response)=>{const payload=await response.json() as LedgerData&{error?:string};if(!response.ok)throw new Error(payload.error||"총계정원장을 불러오지 못했습니다.");if(!cancelled){setData(payload);setFrom(payload.from);setTo(payload.to);}}).catch((caught)=>{if(!cancelled)setError(caught instanceof Error?caught.message:"총계정원장을 불러오지 못했습니다.");});return()=>{cancelled=true;};},[]);
  const selected=useMemo(()=>data?.accounts.find((row)=>String(row.key)===account),[account,data]);
  function download(){const params=new URLSearchParams({from,to,format:"csv"});if(account)params.set("account",account);if(query.trim())params.set("q",query.trim());window.location.href=`/api/finance/general-ledger?${params}`;}
  return <><div className="finance-subpage-heading general-ledger-heading"><div><p>GENERAL LEDGER</p><h2>총계정원장·2026 시산표</h2><span>승인된 개시 기준선에 실제 전기된 2026 분개만 이어서 조회합니다.</span></div><div><button type="button" onClick={download}>CSV 내려받기</button></div></div>
    {error&&<div className="data-governance-message error">{error}</div>}
    <OpeningBalanceControl />
    <section className="general-ledger-controls panel"><label>시작일<input type="date" min="2026-01-01" max={data?.asOf} value={from} onChange={(event)=>setFrom(event.target.value)}/></label><label>종료일<input type="date" min="2026-01-01" max={data?.asOf} value={to} onChange={(event)=>setTo(event.target.value)}/></label><label>계정<select value={account} onChange={(event)=>{setAccount(event.target.value);void load(from,to,event.target.value,query);}}><option value="">전체 계정</option>{data?.accounts.map((row)=><option value={String(row.key)} key={String(row.key)}>{String(row.accountCode||"—")} · {String(row.accountName)}</option>)}</select></label><label>전표·적요 검색<input value={query} placeholder="전표번호, 거래처, 적요" onChange={(event)=>setQuery(event.target.value)}/></label><button type="button" disabled={busy} onClick={()=>void load()}>{busy?"조회 중…":"조회"}</button></section>
    <section className="general-ledger-quality"><article className={data?.totals.openingDifference===0?"pass":"fail"}><span>개시 차대변</span><strong>{data?.totals.openingDifference===0?"일치":"불일치"}</strong><small>{data?.sources.opening.label} · {data?.sources.opening.asOf}</small></article><article className={data?.totals.periodDifference===0?"pass":"fail"}><span>당기 차대변</span><strong>{won(data?.totals.periodDebit)}</strong><small>차이 {won(data?.totals.periodDifference)} · 전기 완료만</small></article><article className={data?.totals.endingDifference===0?"pass":"fail"}><span>기말 차대변</span><strong>{data?.controls.balanced?"일치":"불일치"}</strong><small>차 {won(data?.totals.endingDebit)} · 대 {won(data?.totals.endingCredit)}</small></article><article><span>전기 원천</span><strong>{Number(data?.sources.controlledPostingLines??0)+Number(data?.sources.paymentJournalLines??0)}행</strong><small>통제분개 {data?.sources.controlledPostingLines??0} · 지급전표 {data?.sources.paymentJournalLines??0}</small></article></section>
    <section className="panel general-trial-balance"><header><div><p>LIVE TRIAL BALANCE</p><h3>{selected?`${String(selected.accountName)} 계정 요약`:"2026 합계잔액시산표"}</h3><span>개시잔액 + 조회기간 전기 합계 + 계산된 기말잔액</span></div><em>{data?.accounts.length??0}개 계정</em></header><div className="general-ledger-table trial"><div className="head"><span>계정</span><span>개시 차변</span><span>개시 대변</span><span>당기 차변</span><span>당기 대변</span><span>기말 차변</span><span>기말 대변</span><span>행</span></div>{data?.accounts.filter((row)=>!account||String(row.key)===account).map((row)=><div key={String(row.key)}><p><strong>{String(row.accountCode||"—")}</strong><small>{String(row.accountName)}</small></p><span>{Number(row.openingDebit)?won(row.openingDebit):"—"}</span><span>{Number(row.openingCredit)?won(row.openingCredit):"—"}</span><span>{Number(row.periodDebit)?won(row.periodDebit):"—"}</span><span>{Number(row.periodCredit)?won(row.periodCredit):"—"}</span><b>{Number(row.endingDebit)?won(row.endingDebit):"—"}</b><b>{Number(row.endingCredit)?won(row.endingCredit):"—"}</b><em>{Number(row.lineCount)}행</em></div>)}</div></section>
    <section className="panel general-ledger-lines"><header><div><p>POSTED JOURNAL LINES</p><h3>전기 분개 상세</h3><span>검증 스테이징과 Clobe 원문은 포함하지 않습니다.</span></div><em>{data?.pagination.total??0}행 중 {data?.pagination.returned??0}행</em></header><div className="general-ledger-table lines"><div className="head"><span>일자·전표</span><span>계정·적요</span><span>거래처·부서</span><span>차변</span><span>대변</span><span>원천·전기시각</span></div>{data?.rows.map((row)=><div key={String(row.id)}><p><strong>{String(row.voucherDate)}</strong><small>{String(row.voucherNumber)} · {Number(row.lineNumber)}행</small></p><p><strong>{String(row.accountCode||"—")} · {String(row.accountName)}</strong><small>{String(row.description||"적요 없음")}</small></p><p><strong>{String(row.partnerName||"—")}</strong><small>{String(row.departmentName||"부서 없음")}</small></p><b>{Number(row.debitAmount)?won(row.debitAmount):"—"}</b><b>{Number(row.creditAmount)?won(row.creditAmount):"—"}</b><p><strong>{String(row.sourceType)==="CONTROLLED_POSTING"?"통제 분개":"지급 전표"}</strong><small>{dateTime(row.postedAt)}</small></p></div>)}{!data?.rows.length&&<div className="finance-empty">선택한 조건에 전기된 분개가 없습니다.</div>}</div></section>
    <div className="chart-coverage-note general-ledger-note"><span>i</span>이 화면은 운영 장부입니다. 2026 Clobe 원문과 파일 검증 결과는 승인·전기되기 전까지 합산하지 않습니다.</div></>;
}
